[mgr]
border_style = "rounded"
show_hidden = true
ratio = [2, 4, 6]

[preview]
tab_size = 2
max_height = 1080
max_width = 900
cache_dir = ""
iamge_quality = 75
ueberzug_scale = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
pdf = [
      { run = 'zathura "$@"', desc = "Open with Zathura", block = true, for = "unix" }
]
edit = [
{ run = 'nvim "$@"', desc = "Open with Neovim", block = true, for = "unix" }
]
img = [
{ run = 'feh -d --scale-down --auto-zoom --geometry 1200x800 --no-menus --image-bg 1d2021', desc = "Open with feh", block = true, for = "unix" }
]

[open]
prepend_rules = [
{ name = "*.pdf", use = "pdf" },
{ name = "*.png", use = "img" },
{ name = "*.jpg", use = "img" },
{ name = "*.jpeg", use = "img" }
]
