format = """
[▓▓▓](#282828)\
[ 󰣇 ](bg:#282828 fg:#ebdbb2)\
[](bg:#d65d0e fg:#282828)\
$directory\
[](fg:#d65d0e bg:#282828)\
$git_branch\
$git_status\
[](fg:#282828 bg:#3c3836)\
$c\
$rust\
$golang\
$python\
$php\
$zig\
[](fg:#3c3836 bg:#504945)\
$time\
[ ](fg:#504945)\
\n$character
"""

[directory]
style = "fg:#ebdbb2 bg:#d65d0e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol  $branch ](fg:#689d6a bg:#282828)]($style)'

[git_status]
style = "bg:#282828"
format = '[[($all_status$ahead_behind )](fg:#98971a bg:#282828)]($style)'

[c]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[rust]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[golang]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[php]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[python]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[zig]
symbol = ""
style = "bg:#3c3836"
format = '[[ $symbol  ($version) ](fg:#d79921 bg:#3c3836)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#504945"
format = '[[   $time ](fg:#ebdbb2 bg:#504945)]($style)'

